name: docker

on:
  repository_dispatch:
    types: [trigger-workflow-2]

jobs:
  build-docker-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          ref: ${{ github.event.client_payload.sha }}
          push: true
          tags: jorainer/spectra_tutorials:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
