name: push-to-docker
on:
  push:
    branches: [ master ]
  steps:
      - name: dockerhub-login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: build-and-push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          repository: jorainer/spectra_tutorials
          tag_with_ref: true
          tag_with_sha: true
          tags: latest

      - name: image-digest
        run: echo ${{ steps.docker_build.outputs.digest }}
